#!/bin/bash

set -x

# remove all traces

if docker inspect psftw-blog-nginx &> /dev/null; then
	docker kill psftw-blog-nginx && docker rm -v psftw-blog-nginx
fi

docker inspect psftw-blog &> /dev/null && docker rm -v psftw-blog

if docker inspect psftw/psftw-blog-nginx &> /dev/null; then
	docker rmi -f psftw/psftw-blog-nginx
fi

if docker inspect psftw/psftw-blog &> /dev/null; then
	docker rmi -f psftw/psftw-blog
fi
