#!/bin/bash

set -x

if docker inspect psftw-blog-nginx &> /dev/null; then
	docker kill psftw-blog-nginx
	docker rm -v psftw-blog-nginx
fi

docker inspect psftw-blog &> /dev/null && docker rm -v psftw-blog

docker inspect psftw/psftw-blog-nginx &> /dev/null \
	&& docker rmi -f psftw/psftw-blog-nginx

docker inspect psftw/psftw-blog &> /dev/null \
	&& docker rmi -f psftw/psftw-blog
