#!/bin/bash

set -x

./tinker

docker build -t psftw/psftw-blog-nginx nginx

if docker inspect psftw-blog-nginx &> /dev/null; then
	docker kill psftw-blog-nginx
	docker rm -v psftw-blog-nginx
fi

docker run -d --name psftw-blog-nginx \
	--volumes-from psftw-blog -p 8080:80 \
	psftw/psftw-blog-nginx
